version: "2.12"

services:
  web:
    build: Tools
    ports: 
      - 8080:80

  bot:
    build: DiscordBot
    environment:
      - DISCORD_TOKEN=$TOKEN
      - DISCORD_TOKEN_TEST=$TOKEN_TEST
      - BSU=$BSU_SERVER
      - BotTestingServer=$BotTestingServer
