FROM python:latest
LABEL Maintainer="Grant"
WORKDIR /app

RUN python3 -m pip install -U discord.py
RUN python3 -m pip install -U python-dotenv

RUN mkdir ./Databases
RUN mkdir ./cogs
COPY *.py ./
COPY cogs/*.py ./cogs/

CMD [ "python", "./main.py"]
CMD  python -o ./main.py
