FROM python:latest
LABEL Maintainer="Grant"
WORKDIR /home/delphi/Docker/SnipingBot

RUN python3 -m pip install -U discord.py
RUN python3 -m pip install -U python-dotenv

COPY *.py ./
COPY cogs/*.py ./cogs

CMD [ "python", "./main.py"]
